### ISSUE TITLE
Create a package for NPM

### ISSUE THREAD

**Issue by astr0sl0th** [hackernoon/pixel-icon-library#7]
Hi would you like some help creating a NPM package for the icons so people can use them in react/angular/vue?

**Comment by rex12543** [comment]
Sounds Good! We'd really appreciate you contributing to our Icon Library. Feel free to discuss the details in this thread.
Also, do you need us to start a dedicated branch for this?

**Comment by davidsmooke** [comment]
No worries, NPMJS is already live! https://www.npmjs.com/package/@hackernoon/pixel-icon-library
